### ISSUE TITLE
User Agent style for href hyperlinks and focusable elements

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml-core#128]

**Comment by fred-wang** [comment]
WebKit changed to `:focus-visible` in https://github.com/WebKit/WebKit/pull/61231

**Comment by bkardell** [comment]
Just to clarify, WebKits styles are now (since they are diff than 2019)

```css
:any-link {
    color: -webkit-link;
    cursor: auto;
}

:any-link:active {
    color: -webkit-activelink;
}

:focus-visible {
    outline-style: auto;
}
```
